Economist/Economist/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from finance.views import auth, register

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^', include('finance.urls', namespace="finance")),
    url(r'^auth/reg', register, name='register'),
    url(r'^auth/auth', auth, name='auth'),

]

Economist/finance/urls.py
from finance.views import *
from django.conf.urls import url, include

urlpatterns = [
    url(r'^$', accounts_view, name="accounts_view"),
    url(r'^account/(?P<pk>[0-9]+)/$', account_details, name='account_details'),
    url(r'^contacts/$', contacts_list, name='contacts'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^stats/$', stats_view, name='stats'),
    url(r'^profile/search_profile$', search_contact, name='search_contact'),
    url(r'^profile_form/(?P<id>\d+)/$', profile_form, name='profile_form'),
    url(r'^change_login_password/$', change_login_password, name='change_login_password'),
]

Economist/finance/forms.py
from django import forms
from datetime import date

from django.forms import SelectDateWidget

from .models import Charge, Account, User
from django.core.exceptions import ValidationError
import re


class ChargeForm(forms.ModelForm):
    amount = forms.DecimalField(label = 'Сумма', required = True)
    transacted_at = forms.DateField(label = 'Дата', required = True)

    class Meta:
        model = Charge
        fields = ("transacted_at", "amount")


class AccountForm(forms.ModelForm):
    _total = forms.DecimalField(label='Начальное состояние', required = True)
    name = forms.CharField(label='Имя счета', max_length=20)
    number = forms.CharField(label='Номер счета', max_length=30)
    class Meta:
        model = Account
        fields = ("_total", "name", "number")


class ProfileForm(forms.ModelForm):
    #username = forms.CharField(label='Логин', max_length=16, min_length=5)
    first_name = forms.CharField(label='Имя', max_length=16)
    last_name = forms.CharField(label='Фамилия', max_length=16)
    address = forms.CharField(label='Адрес', max_length=50)
    phone_number = forms.CharField(label='Телефонный номер', max_length=16)
    email = forms.CharField(label='Электронная почта', max_length=32)
    #password = forms.CharField(label='Пароль', min_length=8)
    class Meta:
        model = User
        fields = ("address", "phone_number", "email", "first_name", "last_name")
    def clean(self):
        cleaned_data = super(ProfileForm, self).clean()
        phone_number = cleaned_data.get('phone_number')
        email = cleaned_data.get('email')
        if re.fullmatch(r'\+[1-9][0-9]{10}', phone_number) and len(phone_number) == 12:
            if re.fullmatch(r'(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)', email):
                return cleaned_data
            else:
                self.add_error('email', "Неверный формат адреса электронной почты")
                raise ValidationError("Неверный формат адреса электронной почты")
        else:
            self.add_error('phone_number', "Неверный формат телефонного номера")
            raise ValidationError("Неверный формат телефонного номера")


class PasswordForm(forms.ModelForm):
    username = forms.CharField(label='Логин', max_length=16, min_length=5)
    password = forms.CharField(label='Пароль', min_length=5)
    class Meta:
        model = User
        fields = ("username", "password")
    def clean(self):
        cleaned_data = super(PasswordForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        if re.fullmatch(r'[a-zA-Z0-9]{5,16}', username):
            if re.fullmatch(r'[a-zA-Z0-9]{6,}', password):
                return cleaned_data
            else:
                self.add_error('password', "Пароль должен состоять только из цифр и латинских букв")
                raise ValidationError("Пароль должен состоять только из цифр и латинских букв")
        else:
            self.add_error('username', "Логин должен состоять только из цифр и латинских букв")
            raise ValidationError("Логин должен состоять только из цифр и латинских букв")


class RegistrationForm(forms.ModelForm):
    username = forms.CharField(label='Логин', max_length=16, min_length=5)
    password = forms.CharField(label='Пароль', min_length=8)
    first_name = forms.CharField(label='Имя', max_length=16)
    last_name = forms.CharField(label='Фамилия', max_length=16)
    address = forms.CharField(label='Адрес', max_length=50)
    phone_number = forms.CharField(label='Телефонный номер', max_length=16)
    email = forms.CharField(label='Электронная почта', max_length=32)
    class Meta:
        model = User
        fields = ("username", "password", "address", "phone_number", "email", "first_name", "last_name")
    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        phone_number = cleaned_data.get('phone_number')
        email = cleaned_data.get('email')
        if re.fullmatch(r'[a-zA-Z0-9]{5,16}', username):
            if re.fullmatch(r'[a-zA-Z0-9]{8,}', password):
                if re.fullmatch(r'\+[1-9][0-9]{10}', phone_number) and len(phone_number) == 12:
                    if re.fullmatch(r'(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)', email):
                        return cleaned_data
                    else:
                        self.add_error('email', "Неверный формат адреса электронной почты")
                        raise ValidationError("Неверный формат адреса электронной почты")
                else:
                    self.add_error('phone_number', "Неверный формат телефонного номера")
                    raise ValidationError("Неверный формат телефонного номера")
            else:
                self.add_error('password', "Пароль должен состоять только из цифр и латинских букв")
                raise ValidationError("Пароль должен состоять только из цифр и латинских букв")
        else:
            self.add_error('username', "Логин должен состоять только из цифр и латинских букв")
            raise ValidationError("Логин должен состоять только из цифр и латинских букв")

Economist/finance/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, render_to_response
from datetime import date

from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
# Create your views here.

from .models import Account, Charge, User, Contacts
from .forms import ChargeForm, AccountForm, ProfileForm, PasswordForm
from .decorators import security

@login_required
def stats_view(request):
    return render(request, "finance/views/stats.html", {'user': request.user})

@login_required
def add_contacts(request):
    if request.method == 'POST':
        user = request.user
        if not user.contacts:
            contacts = Contacts()
            contacts.owner = user
            contacts.save()

        else:
            contacts = user.contacts

        try:
            contact = User.objects.get(pk=request.POST['pk'])
        except User.DoesNotExist:
            return HttpResponse(status=404)
        contacts.add_contact(contact)
        return HttpResponse(status=200)

@login_required
def search_contact(request):
    if request.method == 'POST':
        if not 'username' in request.POST:
            return HttpResponse(status=400)

        username = request.POST['username']
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return HttpResponse(status=404)

        contacts = Contacts.objects.filter(owner=request.user)
        if not contacts.exists():
            contacts = Contacts()
            contacts.owner = user
            contacts.save()

        else:
            contacts = contacts[0]

        contacts.add_contact(user)
        contact = '{"username": "' + user.username + '", "pk":' + str(user.pk) +'}'
        return HttpResponse(contact, status=200)

@login_required
def contacts_list(request):
    user = request.user
    contacts = Contacts.objects.filter(owner=user)
    if not contacts.exists():
        contacts = Contacts()
        contacts.owner = user
        contacts.save()

    else:
        contacts = contacts[0]
    return render(request, "finance/views/contacts_list.html", {'contacts': contacts.contacts.all()})

def accounts_view(request):
    user = request.user
    if (not user.is_authenticated()):
        context = RequestContext(request,
                             {'request': request,
                              'user': request.user})
        return render_to_response('finance/views/index.html', context_instance=context)
    if request.method == "POST":
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.user = user
            account.save()
    else:
        form = AccountForm()

    return render(request,
                  'finance/views/accounts_view.html',
                  {"accounts": user.account.all(), 'form': form, 'user':user})


@login_required
@security
def account_details(request, pk):
    account = Account.objects.get(pk=pk)
    if request.method == "POST":
        form = ChargeForm(request.POST)
        if form.is_valid():
            charge = form.save(commit=False)
            account.add_charge(charge)
    else:
        form = ChargeForm()

    charges = account.charges
    months = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль',
              'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']
    curr_year = date.today().year
    statistics = []
    for month in range(1, 13):
        month_charges = charges.filter(transacted_at__month=month, transacted_at__year=curr_year).all()
        income = 0
        outcome = 0
        for charge in month_charges:
            if charge.value > 0:
                income += charge.value
            else:
                outcome += charge.value

        statistic = {'month': months[month - 1], 'income': income, 'outcome': outcome}
        statistics.append(statistic)
    return render(request,
                  'finance/views/account_details_view.html',
                  {'form': form, 'account': account, 'statistics': statistics})


@login_required
def profile(request):
    context = {'name': request.user.username,
               'password': request.user.password,
               'address': request.user.address,
               'email': request.user.email,
               'phone_number': request.user.phone_number,
               'id': request.user.id,
               'accounts': request.user.account.all()
               }
    return render(request, 'finance/views/profile.html', context)

@login_required
def profile_form(request, id):
    user = request.user
    info = ''
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            #user.set_password(form.cleaned_data['password'])
            user.save()
            info = 'Изменения сохранены!'
        else:
            info = 'Что-то пошло не так...'
    else:
        form = ProfileForm(instance=user)
    return render(
        request, 'finance/views/profile_form.html',
        {'form': form, 'info': info, 'id': id}
    )

@login_required
def change_login_password(request):
    user = request.user
    info = ''
    if request.method == "POST":
        form = PasswordForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])

            user.save()
            user = authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password'])
            login(request, user)
            info = 'Логин и пароль были успешно изменены!'
        else:
            info = 'Что-то пошло не так...'
    else:
        form = PasswordForm()
    return render(
        request, 'finance/views/change_login_password.html',
        {'form': form, 'info': info}
    )

@csrf_exempt
def auth(request):
    if request.method == 'POST':
        if 'login' in request.POST:
            username = request.POST['login']
            if 'password' in request.POST:
                password = request.POST['password']
                user = authenticate(username=username, password=password)
                if user:
                    login(request, user)
                    return HttpResponse(status=200)
                else:
                    return HttpResponse(status=401)  # Unauthorized

            else:
                return HttpResponse(status=400)  # BadRequest
        else:
            return HttpResponse(status=400)  # BadRequest


@csrf_exempt
def register(request):
    if request.method == 'POST':
        if 'login' in request.POST:
            username = request.POST['login']
            if 'password' in request.POST:
                password = request.POST['password']
                user = User.objects.create_user(username=username, password=password, email='')
                user.phone_number = ''
                user.address = ''
                user.save()
                user = authenticate(username=username, password=password)
                if user:
                    login(request, user)
                    return HttpResponse(status=200)
                else:
                    return HttpResponse(status=401)  #Unauthorized

            else:
                return HttpResponse(status=400)  # BadRequest
        else:
            return HttpResponse(status=400)  # BadRequest


@login_required
@security
def delete_account(request, pk):
    Account.objects.get(pk=pk).delete()
    return HttpResponse(status=200)

@login_required
def delete_charge(request, pk):
    Charge.objects.get(pk=pk).delete()
    return HttpResponse(status=200)

Economist/finance/templates/finance/views/account_details_view.html
{% extends 'finance/base.html' %}
{% block title%} Транзакции {% endblock %}
{% block css_import %}
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
{% endblock %}
{% block content %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

        <h3>Транзакции по счету: "{{ account.name }}"</h3>
        <h4>Баланс {{ account.total }}</h4>
        <table class="bordered highlight" >
            <thead>
                <tr>
                    <th>Сумма транзакции</th>
                    <th>Дата</th>
                </tr>
            </thead>
            <tbody>
                {% for charge in account.charges_ordered %}
                <tr>
                    <td>{{ charge.value }}</td>
                    <td>{{ charge.date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    <div class="fixed-action-btn horizontal">
    <a class="btn-floating btn-large blue" id="btn_link">
      <i class="large material-icons">add</i>
    </a>
  </div>
        <div id="statistics">
            {% for statistic in statistics %}
                {% if statistic.income or statistic.outcome %}
                <div id="statistic" data-month="{{ statistic.month }}"
                     data-income="{{ statistic.income }}" data-outcome="{{ statistic.outcome }}"></div>
                {% endif %}
            {% endfor %}
        </div>
        <div id="statistics_bar" style="height: 250px;"></div>

    <script>
        $(document).ready(function () {
            $("#create_form").hide();
            $("#btn_link").on('click', function () {
                $("#create_form").fadeIn();
            });
            $(document).mousedown(function (e) {
                var container = $(".post-form");
                if (!container.is(e.target) // если клик был не по нашему блоку
                    && container.has(e.target).length === 0) { // и не по его дочерним элементам
                    $("#create_form").hide();
                }
            });
        })
    </script>

        <div class="row" id="create_form" style=" width:100%; min-height:100%;
                overflow:visible;
                position:fixed;
                top:0;">
            <div class="col s4"  style="left: 30%; top:20%; position:fixed;">
                <div class="card z-depth-2">
                    <div class="card-header  blue darken-1">
                        <nav>
                                <div class="nav-wrapper  blue darken-1">
                                    <div class="col s12" style="padding-left:30px">
                                        <a class="breadcrumb  blue darken-1 center-align">Добавить транзакцию</a>
                                    </div>
                                </div>
                            </nav>
                        </div>
                    <div class="card-content">
                    <form method="POST" class="post-form">{% csrf_token %}
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="save btn btn-default blue darken-1">Добавить</button>
                    </form>
                        </div>
                </div>
            </div>
        </div>

{% endblock %}

Economist/finance/templates/finance/views/accounts_view.html
{% extends 'finance/base.html' %}
{% load staticfiles %}
{% block tittle %}Счета{% endblock %}
{% block content %}

    <table class="bordered highlight" >
        <tbody>
            {% for account in accounts %}
            <tr>
                <td>{% include "finance/elements/account_preview.html" with account=account %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="fixed-action-btn horizontal">
    <a class="btn-floating btn-large blue" id="btn_link">
      <i class="large material-icons">add</i>
    </a>
  </div>
    <script>
        $(document).ready(function () {
            $("#create_form").hide();
            $("#btn_link").on('click', function () {
                $("#create_form").fadeIn();
            });
            $(document).mousedown(function (e) {
                var container = $(".post-form");
                if (!container.is(e.target) // если клик был не по нашему блоку
                    && container.has(e.target).length === 0) { // и не по его дочерним элементам
                    $("#create_form").hide();
                }
            });
        })
    </script>

        <div class="row" id="create_form" style=" width:100%; min-height:100%;
                overflow:visible;
                position:fixed;
                top:0;">
            <div class="col s4"  style="left: 30%; top:20%; position:fixed;">
                <div class="card z-depth-2">
                    <div class="card-header  blue darken-1">
                        <nav>
                                <div class="nav-wrapper  blue darken-1">
                                    <div class="col s12" style="padding-left:30px">
                                        <a class="breadcrumb  blue darken-1 center-align">Добавить счет</a>
                                    </div>
                                </div>
                            </nav>
                        </div>
                    <div class="card-content">
                    <form method="POST" class="post-form">{% csrf_token %}
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="save btn btn-default blue darken-1">Добавить</button>
                    </form>
                        </div>
                </div>
            </div>
        </div>
{% endblock %}

Economist/finance/templates/finance/views/change_login_password.html
{% extends 'finance/base.html' %}
{% load staticfiles %}
{% block tittle %}Редактирование профиля{% endblock %}
{% block content %}
    <form action="{% url 'finance:change_login_password' %}" method="post">
		{% csrf_token %}
        {% for field in form.visible_fields %}
            <p>{{ field.label }}:</p>
			{{ field }}
			{% for error in field.errors %}
				{{ error }}
			{% endfor %}
        {% endfor %}
		{{ info }}
        <br>
		<br>
        <button type="submit">Изменить</button>
    </form>
	<br>
	<a href="{% url 'finance:profile' %}">Вернуться на страницу профиля</a>
{% endblock %}

Economist/finance/templates/finance/views/contacts_list.html
{% extends "finance/base.html" %}
{% block content %}
<div class="card">
    <div class="row">

        <form method="POST">
            {% csrf_token %}
            <div class="input-field col s8">
                <i class="material-icons prefix">search</i>
                <input id="username" type="tel" class="validate">
                <label for="username">Добавить (Имя пользователя)</label>
            </div>
            <div class="col s4">
            <a class="waves-effect waves-light btn blue darken 1" style="top:13px" id="search_contact">Найти</a>
            </div>
        </form>

    </div>
</div>
<table class="bordered highlight" >
    <tbody>
        {% for contact in contacts %}
        <tr>
            <td>{% include "finance/elements/contactview.html" with contact=contact %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="row" id="add_form" style=" width:100%; min-height:100%;
                overflow:visible;
                position:fixed;
                top:0;">
            <div class="col s4"  style="left: 30%; top:20%; position:fixed;">
                <div class="card z-depth-2">
                    <div class="card-header  blue darken-1">
                        <nav>
                                <div class="nav-wrapper  blue darken-1">
                                    <div class="col s12" style="padding-left:30px">
                                        <a class="breadcrumb  blue darken-1 center-align">Добавить контакт</a>
                                    </div>
                                </div>
                            </nav>
                        </div>
                    <div class="card-content">
                    <form method="POST" class="post-form">{% csrf_token %}
                        {% csrf_token %}
                        <h3 id="add_contact_text"></h3>
                        <button type="submit" class="save btn btn-default blue darken-1">Добавить</button>
                    </form>
                        </div>
                </div>
            </div>
        </div>
<script>
    $(document).ready(function () {
        $('#add_form').hide();
        $("#search_contact").on('click', function () {
            event.preventDefault();
            var type = "main_task";
            $.ajax({
                type: 'POST',
                url: '/profile/search_profile',
                data:{
                    username:$('#username').val(),
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                },
                success:function(contact_json) {
                    Materialize.toast('Пользователь добавлен', 4000);
                    location.reload();
                },
                error: function () {
                    Materialize.toast('Пользователь не найден', 4000);
                }
            });
        })
    })
</script>
{% endblock %}

Economist/finance/templates/finance/views/profile.html
{% extends 'finance/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
    <div class="col s2"></div>
    <div class="col">
        <p>Логин: {{ name }}</p>
        <p>Адрес: {{ address }}</p>
        <p>Электронная почта: {{ email }}</p>
        <p>Номер телефона: {{ phone_number }}</p>
        <a href = "{% url 'finance:profile_form' id=id %}">Изменить профиль</a>
        <br>
        <a href = "{% url 'finance:change_login_password' %}">Изменить логин и пароль</a>
    </div>
</div>
{% endblock %}

Economist/finance/templates/finance/views/profile_form.html
{% extends 'finance/base.html' %}
{% load staticfiles %}
{% block tittle %}Редактирование профиля{% endblock %}
{% block content %}
    <form action="{% url 'finance:profile_form' id=id %}" method="post">
		{% csrf_token %}
        {% for field in form.visible_fields %}
            <p>{{ field.label }}:</p>
            {{ field }}
			{% for error in field.errors %}
				{{ error }}
			{% endfor %}
        {% endfor %}
		{{ info }}
        <br>
		<br>
        <button type="submit">Изменить</button>
    </form>
	<br>
	<a href="{% url 'finance:profile' %}">Вернуться на страницу профиля</a>
{% endblock %}

Economist/finance/templates/finance/views/stats.html
{% extends "finance/base.html" %}
{% block content %}
        <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
    <div class="row">
        <div class="col s6 m6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Последние тразакции</span>
                    <div class="collection">
                        {% for charge in user.last_transactions %}
                            <a class="collection-item">
                                <p>{{ charge.account.name }}: {{ charge.value }} - {{ charge.date }}</p>
                            </a>
                        {%endfor%}
                    </div>
                </div>
            </div>
        </div>
        <div class="col s6 m6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Статистика баланса</span>
                    <div id="statistics_bar" style="height: 250px;"></div>
                </div>
            </div>
        </div>

    </div>
    <div id="statistics">
        {% for statistic in user.balance_statistic %}
            <div id="statistic" data-date="{{ statistic.date }}"  data-balance="{{ statistic.balance }}"></div>
        {% endfor %}
    </div>




    <script>
        $(document).ready(function () {
            var data = [];
            var statistics = $("#statistics").children();
            for ( i = 0; i < statistics.length; i++ ){
                var date = $(statistics[i]).data("month");
                var balance = $(statistics[i]).data("balance");
                if (balance) {
                    balance = parseFloat(balance.replace(/[,]+/g, '.'));
                } else {
                    balance = 0;
                }

                //outcome = parseFloat(outcome.substring(1, outcome.length - 1).replace(/[,]+/g, '.'));
                var statistic = { date: i, balance: balance};
                data.push(statistic);
            }
            Morris.Line({
              element: 'statistics_bar',
              data: data,
              xkey: 'date',
              ykeys: ['balance']
            });
        });

    </script>
{% endblock %}